### ISSUE TITLE
Apps no longer run on Android with this plugin installed

### ISSUE THREAD

**Issue by spiro-angelakis** [Shin-NiL/Godot-Android-Admob-Plugin#147]
**Godot version:**
tried on 3.2.3 and also 3.3
**AdMob Plugin version:**

**Issue description:**

after installing this plugin ( any version of it, even 5), the app will no longer boot on the android device, when it worked just fine on android before hand, ive tested and tried every which way not sure what to do sadly

**Comment by spiro-angelakis** [comment]
2021-04-24 08:00:27.481 25732-25918/com.sprvlln.spaceshipsurvival E/godot: **ERROR**: Couldn't find singleton for class: org/godotengine/godot/GodotAdMob.
2021-04-24 08:00:27.481 25732-25918/com.sprvlln.spaceshipsurvival E/godot:    At: platform/android/java_godot_lib_jni.cpp:105:_initialize_java_modules() - Condition "!singletonClass" is true. Continuing.
2021-04-24 08:00:27.485 25732-25918/com.sprvlln.spaceshipsurvival E/AndroidRuntime: FATAL EXCEPTION: GLThread 90378
    Process: com.sprvlln.spaceshipsurvival, PID: 25732
    java.lang.ClassNotFoundException: Didn't find class "org/godotengine/godot/GodotAdMob" on path: DexPathList[[zip file "/data/app/com.sprvlln.spaceshipsurvival-BdnOOAoHVP2tCwkBU8dDQg==/base.apk"],nativeLibraryDirectories=[/data/app/com.sprvlln.spaceshipsurvival-BdnOOAoHVP2tCwkBU8dDQg==/lib/arm64, /data/app/com.sprvlln.spaceshipsurvival-BdnOOAoHVP2tCwkBU8dDQg==/base.apk!/lib/arm64-v8a, /system/lib64, /product/lib64]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:196)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at org.godotengine.godot.GodotLib.setup(Native Method)
        at org.godotengine.godot.Godot$2.run(Godot.java:392)
        at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1502)
        at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1272)

**Comment by spiro-angelakis** [comment]
nEVERMIND! Sorry i was just messing up
