### ISSUE TITLE
Godot 3.3.2 org.godotengine.godot.Godot cannot be cast to android.app.Activity

### ISSUE THREAD

**Issue by SanderVanhove** [Shin-NiL/Godot-Android-Admob-Plugin#162]
**Godot version:** 3.3.2

**AdMob Plugin version:** 5.0.0

**Issue description:**

When I call `play_games_services.init(false)` I get this error in my logcat:

```
AndroidRuntime: Process: com.sandervanhove.bouncybox, PID: 27870
AndroidRuntime: java.lang.ClassCastException: org.godotengine.godot.Godot cannot be cast to android.app.Activity
AndroidRuntime:        at io.cgisca.godot.gpgs.PlayGameServicesGodot.initialize(PlayGameServicesGodot.kt:185)
AndroidRuntime:        at io.cgisca.godot.gpgs.PlayGameServicesGodot.init(PlayGameServicesGodot.kt:168)
AndroidRuntime:        at org.godotengine.godot.GodotLib.step(Native Method)
AndroidRuntime:        at org.godotengine.godot.GodotRenderer.onDrawFrame(GodotRenderer.java:60)
AndroidRuntime:        at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1582)
AndroidRuntime:        at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1281)
```

Maybe this is related to https://github.com/godotengine/godot/issues/47198.

**Comment by SanderVanhove** [comment]
Woops put this in the wrong repo, please ignore 🤦‍♂️
