### ISSUE TITLE
Google Play Console: Pre-launch report: unsupported APIs warnings

### ISSUE THREAD

**Issue by cgeadas** [Shin-NiL/Godot-Android-Admob-Plugin#19]
**Godot version:**
3.2

**Issue description:**
Pre-launch reports now present warnings relating to unsupported APIs.

In all warnings (10), the mentioned api is ads related, so I figure it's related to this module.

I'm pasting 2 of the warnings. Can attach the rest if required.

```
StrictMode policy violation: android.os.strictmode.NonSdkApiUsedViolation: Ljava/nio/Buffer;->address:J
	at android.os.StrictMode.lambda$static$1(StrictMode.java:428)
	at android.os.-$$Lambda$StrictMode$lu9ekkHJ2HMz0jd3F8K8MnhenxQ.accept(Unknown Source:2)
	at java.lang.Class.getDeclaredField(Native Method)
	at ahv.a(:com.google.android.gms.policy_ads_fdr_dynamite@21001000@21001000.272763194.272763194:6)
	at ahv.b(:com.google.android.gms.policy_ads_fdr_dynamite@21001000@21001000.272763194.272763194:5)
	at ahv.<clinit>(:com.google.android.gms.policy_ads_fdr_dynamite@21001000@21001000.272763194.272763194:10)
	at ahv.a(:com.google.android.gms.policy_ads_fdr_dynamite@21001000@21001000.272763194.272763194:7)
	at agf.<clinit>(:com.google.android.gms.policy_ads_fdr_dynamite@21001000@21001000.272763194.272763194:2)
	at agf.a(:com.google.android.gms.policy_ads_fdr_dynamite@21001000@21001000.272763194.272763194:160)
	at agm.a(:com.google.android.gms.policy_ads_fdr_dynamite@21001000@21001000.272763194.272763194:11)
	at agm.a(:com.google.android.gms.policy_ads_fdr_dynamite@21001000@21001000.272763194.272763194:18)
	at aet.d(:com.google.android.gms.policy_ads_fdr_dynamite@21001000@21001000.272763194.272763194:2)
	at aet.e(:com.google.android.gms.policy_ads_fdr_dynamite@21001000@21001000.272763194.272763194:1)
	at dl.a(:com.google.android.gms.policy_ads_fdr_dynamite@21001000@21001000.272763194.272763194:22)
	at com.google.android.ads.tasks.z.b(:com.google.android.gms.policy_ads_fdr_dynamite@21001000@21001000.272763194.272763194:4)
	at com.google.android.ads.tasks.z.call(Unknown Source:0)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:764)
```

```
StrictMode policy violation: android.os.strictmode.NonSdkApiUsedViolation: Ljava/nio/Buffer;->address:J
	at android.os.StrictMode.lambda$static$1(StrictMode.java:428)
	at android.os.-$$Lambda$StrictMode$lu9ekkHJ2HMz0jd3F8K8MnhenxQ.accept(Unknown Source:2)
	at java.lang.Class.getDeclaredField(Native Method)
	at ahv.a(:com.google.android.gms.policy_ads_fdr_dynamite@21001000@21001000.272763194.272763194:6)
	at ahv.b(:com.google.android.gms.policy_ads_fdr_dynamite@21001000@21001000.272763194.272763194:5)
	at ahv.<clinit>(:com.google.android.gms.policy_ads_fdr_dynamite@21001000@21001000.272763194.272763194:10)
	at ahv.a(:com.google.android.gms.policy_ads_fdr_dynamite@21001000@21001000.272763194.272763194:7)
	at agf.<clinit>(:com.google.android.gms.policy_ads_fdr_dynamite@21001000@21001000.272763194.272763194:2)
	at agf.a(:com.google.android.gms.policy_ads_fdr_dynamite@21001000@21001000.272763194.272763194:160)
	at agm.a(:com.google.android.gms.policy_ads_fdr_dynamite@21001000@21001000.272763194.272763194:11)
	at agm.a(:com.google.android.gms.policy_ads_fdr_dynamite@21001000@21001000.272763194.272763194:18)
	at aex.a(:com.google.android.gms.policy_ads_fdr_dynamite@21001000@21001000.272763194.272763194:20)
	at aex.a(:com.google.android.gms.policy_ads_fdr_dynamite@21001000@21001000.272763194.272763194:25)
	at ns.a(:com.google.android.gms.policy_ads_fdr_dynamite@21001000@21001000.272763194.272763194:5)
	at kj.a(:com.google.android.gms.policy_ads_fdr_dynamite@21001000@21001000.272763194.272763194:11)
	at kb.c(:com.google.android.gms.policy_ads_fdr_dynamite@21001000@21001000.272763194.272763194:7)
	at ke.handleMessage(:com.google.android.gms.policy_ads_fdr_dynamite@21001000@21001000.272763194.272763194:29)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at oy.a(Unknown Source:0)
	at oy.dispatchMessage(Unknown Source:0)
	at android.os.Looper.loop(Looper.java:193)
	at android.os.HandlerThread.run(HandlerThread.java:65)
```

Can this be a matter of minSdk or libraries version?

**Comment by Shin-NiL** [comment]
Maybe because we are using a relatively old version of play-services-ads (16.0.0)? If it's the case, I think you can just ignore this warning, as it's a Google API too.

**Comment by cgeadas** [comment]
> Maybe because we are using a relatively old version of play-services-ads (16.0.0)? If it's the case, I think you can just ignore this warning, as it's a Google API too.

Wouldn't it be useful to determine the minimum version warning-free?
I don't care for devices with less than android 5.1 / api 22, but it might be useful to know the tradeoffs.

**Comment by Shin-NiL** [comment]
I don't think these warnings will prevent you to publish your app for any Android version.
