### ISSUE TITLE
Build failed with an exception

### ISSUE THREAD

**Issue by marcio-pessoa** [Shin-NiL/Godot-Android-Admob-Plugin#195]
**Godot version: 3.4.4**

**AdMob Plugin version: 6.0.0**

**Issue description:**
I updated AdMob Plugin version 5.1.0 to version 6.0.0. After that I got the following error when trying to export to Android:

```
> Task :preBuild UP-TO-DATE
> Task :preDebugBuild UP-TO-DATE
> Task :compileDebugAidl NO-SOURCE
> Task :compileDebugRenderscript NO-SOURCE
> Task :generateDebugBuildConfig UP-TO-DATE
> Task :javaPreCompileDebug UP-TO-DATE
> Task :generateDebugResValues UP-TO-DATE
> Task :generateDebugResources UP-TO-DATE
> Task :checkDebugAarMetadata
> Task :createDebugCompatibleScreenManifests UP-TO-DATE
> Task :extractDeepLinksDebug UP-TO-DATE
> Task :processDebugMainManifest
> Task :processDebugManifest
> Task :mergeDebugNativeDebugMetadata NO-SOURCE
> Task :mergeDebugResources
> Task :mergeDebugShaders UP-TO-DATE
> Task :compileDebugShaders NO-SOURCE
> Task :generateDebugAssets UP-TO-DATE
> Task :mergeDebugAssets
> Task :processDebugJavaRes NO-SOURCE
> Task :compressDebugAssets
> Task :mergeDebugJniLibFolders UP-TO-DATE
> Task :checkDebugDuplicateClasses
> Task :mergeDebugNativeLibs UP-TO-DATE
> Task :stripDebugDebugSymbols UP-TO-DATE
> Task :validateSigningDebug UP-TO-DATE
> Task :writeDebugAppMetadata UP-TO-DATE
> Task :writeDebugSigningConfigVersions UP-TO-DATE
> Task :processDebugManifestForPackage
> Task :mergeDebugJavaResource
> Task :processDebugResources
> Task :desugarDebugFileDependencies
> Task :compileDebugJavaWithJavac
> Task :compileDebugSources
> Task :dexBuilderDebug
> Task :mergeExtDexDebug

> Task :mergeDexDebug FAILED
ERROR:D8: Cannot fit requested classes in a single dex file (# methods: 74260 > 65536)
com.android.builder.dexing.DexArchiveMergerException: Error while merging dex archives: 
The number of method references in a .dex file cannot exceed 64K.
Learn how to resolve this issue at https://developer.android.com/tools/building/multidex.html
	at com.android.builder.dexing.D8DexArchiveMerger.getExceptionToRethrow(D8DexArchiveMerger.java:151)
	at com.android.builder.dexing.D8DexArchiveMerger.mergeDexArchives(D8DexArchiveMerger.java:138)
	at com.android.build.gradle.internal.tasks.DexMergingWorkAction.merge(DexMergingTask.kt:863)
	at com.android.build.gradle.internal.tasks.DexMergingWorkAction.run(DexMergingTask.kt:809)
	at com.android.build.gradle.internal.profile.ProfileAwareWorkAction.execute(ProfileAwareWorkAction.kt:74)
	at org.gradle.workers.internal.DefaultWorkerServer.execute(DefaultWorkerServer.java:63)
	at org.gradle.workers.internal.NoIsolationWorkerFactory$1$1.create(NoIsolationWorkerFactory.java:66)
	at org.gradle.workers.internal.NoIsolationWorkerFactory$1$1.create(NoIsolationWorkerFactory.java:62)
	at org.gradle.internal.classloader.ClassLoaderUtils.executeInClassloader(ClassLoaderUtils.java:97)
	at org.gradle.workers.internal.NoIsolationWorkerFactory$1.lambda$execute$0(NoIsolationWorkerFactory.java:62)
	at org.gradle.workers.internal.AbstractWorker$1.call(AbstractWorker.java:44)
	at org.gradle.workers.internal.AbstractWorker$1.call(AbstractWorker.java:41)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$CallableBuildOperationWorker.execute(DefaultBuildOperationRunner.java:200)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$CallableBuildOperationWorker.execute(DefaultBuildOperationRunner.java:195)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$3.execute(DefaultBuildOperationRunner.java:75)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$3.execute(DefaultBuildOperationRunner.java:68)
	at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:153)
	at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:68)
	at org.gradle.internal.operations.DefaultBuildOperationRunner.call(DefaultBuildOperationRunner.java:62)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.lambda$call$2(DefaultBuildOperationExecutor.java:79)
	at org.gradle.internal.operations.UnmanagedBuildOperationWrapper.callWithUnmanagedSupport(UnmanagedBuildOperationWrapper.java:54)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.call(DefaultBuildOperationExecutor.java:79)
	at org.gradle.workers.internal.AbstractWorker.executeWrappedInBuildOperation(AbstractWorker.java:41)
	at org.gradle.workers.internal.NoIsolationWorkerFactory$1.execute(NoIsolationWorkerFactory.java:59)
	at org.gradle.workers.internal.DefaultWorkerExecutor.lambda$submitWork$2(DefaultWorkerExecutor.java:206)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at org.gradle.internal.work.DefaultConditionalExecutionQueue$ExecutionRunner.runExecution(DefaultConditionalExecutionQueue.java:214)
	at org.gradle.internal.work.DefaultConditionalExecutionQueue$ExecutionRunner.runBatch(DefaultConditionalExecutionQueue.java:164)
	at org.gradle.internal.work.DefaultConditionalExecutionQueue$ExecutionRunner.run(DefaultConditionalExecutionQueue.java:131)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:48)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:61)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: com.android.tools.r8.CompilationFailedException: Compilation failed to complete, position: null
	at Version.fakeStackEntry(Version_3.0.73.java:0)
	at com.android.tools.r8.utils.w.a(SourceFile:68)
	at com.android.tools.r8.utils.w.a(SourceFile:28)
	at com.android.tools.r8.utils.w.a(SourceFile:27)
	at com.android.tools.r8.utils.w.b(SourceFile:3)
	at com.android.tools.r8.D8.run(D8.java:11)
	at com.android.builder.dexing.D8DexArchiveMerger.mergeDexArchives(D8DexArchiveMerger.java:136)
	... 35 more
Caused by: com.android.tools.r8.internal.b: Cannot fit requested classes in a single dex file (# methods: 74260 > 65536)
	at com.android.tools.r8.internal.UA.a(SourceFile:14)
	at com.android.tools.r8.internal.UA.a(SourceFile:22)
	at com.android.tools.r8.dex.z.a(SourceFile:58)
	at com.android.tools.r8.dex.z$h.a(SourceFile:7)
	at com.android.tools.r8.dex.b.a(SourceFile:14)
	at com.android.tools.r8.dex.b.c(SourceFile:36)
	at com.android.tools.r8.D8.d(D8.java:199)
	at com.android.tools.r8.D8.b(D8.java:1)
	at com.android.tools.r8.utils.w.a(SourceFile:24)
	... 38 more


FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':mergeDexDebug'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.DexMergingTaskDelegate
   > There was a failure while executing work items
      > A failure occurred while executing com.android.build.gradle.internal.tasks.DexMergingWorkAction
         > com.android.builder.dexing.DexArchiveMergerException: Error while merging dex archives: 
           The number of method references in a .dex file cannot exceed 64K.
           Learn how to resolve this issue at https://developer.android.com/tools/building/multidex.html

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 3s
27 actionable tasks: 15 executed, 12 up-to-date

Exit Code: 1
```

**Comment by marcio-pessoa** [comment]
Hi dears...

I fixed the issue following instructions found on https://developer.android.com/studio/build/multidex.

I just added `multiDexEnabled = true` on `res://android/build/build.gradle`, like this:

```
android {
    defaultConfig {
        ...
        multiDexEnabled = true
        ...
    }
}
```

I fixed by the right way?

**Comment by Shin-NiL** [comment]
I would suggest just cleaning the build with `./gradlew clean` inside the `android/build` directory.

**Comment by marcio-pessoa** [comment]
Thanks @Shin-NiL 

When I ran `./gradlew clean`:

```
BUILD SUCCESSFUL in 1s
2 actionable tasks: 1 executed, 1 up-to-date
```

But when I try to export to Android I got the same issue.

**Comment by Funmungus** [comment]
I did not reproduce this with this plugin, but I did get this when building the later Android app.  To resolve I had to add multiDexEnabled = true, such as @marcio-pessoa posted.  I also had to add a dependency to androidx.multidex:multidex
`
    dependencies {
    ...
    implementation "androidx.multidex:multidex:latest.release"
    }
`

**Comment by Shin-NiL** [comment]
I'm getting this error with the latest merge...

**Comment by marcio-pessoa** [comment]
Good job, @Shin-NiL !
