### ISSUE TITLE
Error on calling loadRewardedVideo

### ISSUE THREAD

**Issue by dala00** [Shin-NiL/Godot-Android-Admob-Plugin#63]
**Godot version:** 3.2.2

**AdMob Plugin version:** 4.0.0

**Issue description:**

I don't know details why. Just a reporting.

Error occurs when called loadRewardedVideo. Not using admob-lib.

```
2020-07-31 22:21:34.267 20846-25224/? E/SQLiteDatabase: Error inserting period=198000 preferred_charging_state=1 preferred_network_type=1 target_class=com.google.android.gms.measurement.PackageMeasurementTaskService required_network_type=0 runtime=1596201694262 required_idleness_state=0 source=16 service_kind=0 target_package=com.google.android.gms persistence_level=1 source_version=202614000 last_runtime=0 user_id=0 job_id=-1 requires_charging=0 tag=Measurement.PackageMeasurementTaskService.UPLOAD_TASK_TAG flex_time=98000 task_type=0 retry_strategy={"maximum_backoff_seconds":{"3600":0},"initial_backoff_seconds":{"30":0},"retry_policy":{"0":0}}
    android.database.sqlite.SQLiteConstraintException: UNIQUE constraint failed: pending_ops.tag, pending_ops.target_class, pending_ops.target_package, pending_ops.user_id (code 2067 SQLITE_CONSTRAINT_UNIQUE)
        at android.database.sqlite.SQLiteConnection.nativeExecuteForLastInsertedRowId(Native Method)
        at android.database.sqlite.SQLiteConnection.executeForLastInsertedRowId(SQLiteConnection.java:796)
        at android.database.sqlite.SQLiteSession.executeForLastInsertedRowId(SQLiteSession.java:788)
        at android.database.sqlite.SQLiteStatement.executeInsert(SQLiteStatement.java:86)
        at android.database.sqlite.SQLiteDatabase.insertWithOnConflict(SQLiteDatabase.java:1564)
        at android.database.sqlite.SQLiteDatabase.insert(SQLiteDatabase.java:1433)
        at aqnf.a(:com.google.android.gms@202614030@20.26.14 (100408-320008519):175)
        at aqmf.a(:com.google.android.gms@202614030@20.26.14 (100408-320008519):180)
        at aqmf.a(:com.google.android.gms@202614030@20.26.14 (100408-320008519):22)
        at aqmf.a(:com.google.android.gms@202614030@20.26.14 (100408-320008519):175)
        at aqip.run(:com.google.android.gms@202614030@20.26.14 (100408-320008519):9)
        at sin.b(:com.google.android.gms@202614030@20.26.14 (100408-320008519):12)
        at sin.run(:com.google.android.gms@202614030@20.26.14 (100408-320008519):7)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at soi.run(:com.google.android.gms@202614030@20.26.14 (100408-320008519):0)
        at java.lang.Thread.run(Thread.java:764)
```

So now I'm using 3.0.1 (with no problem)

**Comment by Shin-NiL** [comment]
Are you using sqlite by any chance? Or any other plugin?

**Comment by dala00** [comment]
No I'm not using. I'm using only this plugin.

**Comment by Shin-NiL** [comment]
I this project the demo? If not, could you try to run it?
What's your Android version?

**Comment by dala00** [comment]
Android version is 9.
Game was running. Just ad not loaded. (So I didn't notice first. I noticed because loaded callback not called)
My project was not new (my developing game) but just after remove 3.2.1 and installed 3.2.2 custom template.
Just to be sure, I'm going to try again with new project later.

**Comment by Kamyabnz** [comment]
Hi @dala00, how is it going with your new project? Did you solve your issue?

**Comment by dala00** [comment]
Hi @Kamyabnz 

In the end, I resolved by following issue.
https://github.com/Shin-NiL/Godot-Android-Admob-Plugin/issues/84

I'm using Godot3.2.2 and using this plugin4.1.1

**Comment by dala00** [comment]
@Kamyabnz 
Sorry, I'm using 3.0.1 yet...

Only for banner, I solved by following.
https://github.com/Shin-NiL/Godot-Android-Admob-Plugin/issues/84

But I couldn't try reward yet.

**Comment by Kamyabnz** [comment]
Alright so the problem was solved by using the newer version of the plugin and you just tested the banner. I will reopen the issue and let it be open until @Shin-NiL closes this issue.

can you give me the details on how to recreate your environment and test it with rewards?

**Comment by dala00** [comment]
This is part of my program.

```gdscript
extends Node


var _admob = null


func _init():
    if Engine.has_singleton("AdMob"):
        _admob = Engine.get_singleton("AdMob")
        if OS.get_name() == 'iOS':
            _admob.init(!OS.is_debug_build(), get_instance_id())
        else:
            _admob.initWithContentRating(!OS.is_debug_build(), get_instance_id(), false, true, 'G')


func load_rewarded_video(android_id, ios_id):
    if not Engine.has_singleton("AdMob"):
        return false
    
    if OS.get_name() == 'iOS':
        _admob.loadRewardedVideo(ios_id)
    else:
        _admob.loadRewardedVideo(android_id)
    return true
```

**Comment by Shin-NiL** [comment]
@dala00 

Analyzing your code, I notice that you are using an old version of the plugin. My recommendation is to use the newest version, as there may be bugs that have already been fixed.

**Comment by dala00** [comment]
Oh, sorry, this is moving code with 3.0.1... But was almost same.
I'll try reward with newest version sometime and report.
