### ISSUE TITLE
Need an update for 3.2.4+

### ISSUE THREAD

**Issue by gamergamesz** [Shin-NiL/Godot-Android-Admob-Plugin#98]
**Godot 3.2.4:beta1**

**AdMob Plugin version: 4.1.1**

**Issue description:**
Something to do with this https://github.com/godotengine/godot/pull/42186
same with godot share
``` 
10-24 11:27:21.023 31926 31926 E AndroidRuntime:        at java.lang.Class.classForName(Native Method)
10-24 11:27:21.023 31926 31926 E AndroidRuntime:        at java.lang.Class.forName(Class.java:453)
10-24 11:27:21.023 31926 31926 E AndroidRuntime:        at java.lang.Class.forName(Class.java:378)
10-24 11:27:21.023 31926 31926 E AndroidRuntime:        at org.godotengine.godot.plugin.GodotPluginRegistry.loadPlugins(GodotPluginRegistry.java:176)
10-24 11:27:21.023 31926 31926 E AndroidRuntime:        at org.godotengine.godot.plugin.GodotPluginRegistry.<init>(GodotPluginRegistry.java:72)
10-24 11:27:21.023 31926 31926 E AndroidRuntime:        at org.godotengine.godot.plugin.GodotPluginRegistry.initializePluginRegistry(GodotPluginRegistry.java:104)
10-24 11:27:21.023 31926 31926 E AndroidRuntime:        at org.godotengine.godot.Godot.onCreateView(Godot.java:582)
10-24 11:27:21.023 31926 31926 E AndroidRuntime:        at androidx.fragment.app.Fragment.performCreateView(Fragment.java:2439)
10-24 11:27:21.023 31926 31926 E AndroidRuntime:        at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManager.java:1460)
10-24 11:27:21.023 31926 31926 E AndroidRuntime:        at androidx.fragment.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1784)
10-24 11:27:21.023 31926 31926 E AndroidRuntime:        at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManager.java:1852)
10-24 11:27:21.023 31926 31926 E AndroidRuntime:        at androidx.fragment.app.FragmentManagerImpl.dispatchStateChange(FragmentManager.java:3269)
10-24 11:27:21.023 31926 31926 E AndroidRuntime:        at androidx.fragment.app.FragmentManagerImpl.dispatchActivityCreated(FragmentManager.java:3229)
10-24 11:27:21.023 31926 31926 E AndroidRuntime:        at androidx.fragment.app.FragmentController.dispatchActivityCreated(FragmentController.java:201)
10-24 11:27:21.023 31926 31926 E AndroidRuntime:        at androidx.fragment.app.FragmentActivity.onStart(FragmentActivity.java:620)
10-24 11:27:21.023 31926 31926 E AndroidRuntime:        at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1392)
10-24 11:27:21.023 31926 31926 E AndroidRuntime:        at android.app.Activity.performStart(Activity.java:7161)
10-24 11:27:21.023 31926 31926 E AndroidRuntime:        at android.app.ActivityThread.handleStartActivity(ActivityThread.java:2938)
10-24 11:27:21.023 31926 31926 E AndroidRuntime:        at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:186)
10-24 11:27:21.023 31926 31926 E AndroidRuntime:        at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:171)
10-24 11:27:21.023 31926 31926 E AndroidRuntime:        at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:142)
10-24 11:27:21.023 31926 31926 E AndroidRuntime:        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:70)
10-24 11:27:21.023 31926 31926 E AndroidRuntime:        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1809)
10-24 11:27:21.023 31926 31926 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:106)
10-24 11:27:21.023 31926 31926 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:193)
10-24 11:27:21.023 31926 31926 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:6692)
10-24 11:27:21.023 31926 31926 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
10-24 11:27:21.023 31926 31926 E AndroidRuntime:        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
10-24 11:27:21.023 31926 31926 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
```

**Comment by MrZak-dev** [comment]
Same Issue 3.2.4 beta 1
```
11-02 11:00:36.802  3639  3639 E AndroidRuntime: FATAL EXCEPTION: main
11-02 11:00:36.802  3639  3639 E AndroidRuntime: Process: org.godotengine.asteroshoot, PID: 3639
11-02 11:00:36.802  3639  3639 E AndroidRuntime: java.lang.VerifyError: Verifier rejected class shinnil.godot.plugin.android.godotadmob.GodotAdMob: void shinnil.godot.plugin.android.godotadmob.GodotAdMob.<init>(org.godotengine.godot.Godot) failed to verify: void shinnil.godot.plugin.android.godotadmob.GodotAdMob.<init>(org.godotengine.godot.Godot): [0x1E] register v3 has type Reference: org.godotengine.godot.Godot but expected Reference: android.app.Activity (declaration of 'shinnil.godot.plugin.android.godotadmob.GodotAdMob' appears in /data/app/org.godotengine.asteroshoot-taC2dONgXo8GSOibFuBjHg==/base.apk)
11-02 11:00:36.802  3639  3639 E AndroidRuntime:        at java.lang.Class.classForName(Native Method)
11-02 11:00:36.802  3639  3639 E AndroidRuntime:        at java.lang.Class.forName(Class.java:454)
11-02 11:00:36.802  3639  3639 E AndroidRuntime:        at java.lang.Class.forName(Class.java:379)
11-02 11:00:36.802  3639  3639 E AndroidRuntime:        at org.godotengine.godot.plugin.GodotPluginRegistry.loadPlugins(GodotPluginRegistry.java:176)
11-02 11:00:36.802  3639  3639 E AndroidRuntime:        at org.godotengine.godot.plugin.GodotPluginRegistry.<init>(GodotPluginRegistry.java:72)
11-02 11:00:36.802  3639  3639 E AndroidRuntime:        at org.godotengine.godot.plugin.GodotPluginRegistry.initializePluginRegistry(GodotPluginRegistry.java:104)
11-02 11:00:36.802  3639  3639 E AndroidRuntime:        at org.godotengine.godot.Godot.onCreateView(Godot.java:582)
11-02 11:00:36.802  3639  3639 E AndroidRuntime:        at androidx.fragment.app.Fragment.performCreateView(Fragment.java:2439)
11-02 11:00:36.802  3639  3639 E AndroidRuntime:        at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManager.java:1460)
11-02 11:00:36.802  3639  3639 E AndroidRuntime:        at androidx.fragment.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1784)
11-02 11:00:36.802  3639  3639 E AndroidRuntime:        at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManager.java:1852)
11-02 11:00:36.802  3639  3639 E AndroidRuntime:        at androidx.fragment.app.FragmentManagerImpl.dispatchStateChange(FragmentManager.java:3269)
11-02 11:00:36.802  3639  3639 E AndroidRuntime:        at androidx.fragment.app.FragmentManagerImpl.dispatchActivityCreated(FragmentManager.java:3229)
11-02 11:00:36.802  3639  3639 E AndroidRuntime:        at androidx.fragment.app.FragmentController.dispatchActivityCreated(FragmentController.java:201)
11-02 11:00:36.802  3639  3639 E AndroidRuntime:        at androidx.fragment.app.FragmentActivity.onStart(FragmentActivity.java:620)
11-02 11:00:36.802  3639  3639 E AndroidRuntime:        at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1432)
11-02 11:00:36.802  3639  3639 E AndroidRuntime:        at android.app.Activity.performStart(Activity.java:7848)
11-02 11:00:36.802  3639  3639 E AndroidRuntime:        at android.app.ActivityThread.handleStartActivity(ActivityThread.java:3294)
11-02 11:00:36.802  3639  3639 E AndroidRuntime:        at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:221)
11-02 11:00:36.802  3639  3639 E AndroidRuntime:        at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:201)
11-02 11:00:36.802  3639  3639 E AndroidRuntime:        at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:173)
11-02 11:00:36.802  3639  3639 E AndroidRuntime:        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
11-02 11:00:36.802  3639  3639 E AndroidRuntime:        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2016)
11-02 11:00:36.802  3639  3639 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:107)
11-02 11:00:36.802  3639  3639 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:214)
11-02 11:00:36.802  3639  3639 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:7356)
11-02 11:00:36.802  3639  3639 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
11-02 11:00:36.802  3639  3639 E AndroidRuntime:        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
11-02 11:00:36.802  3639  3639 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
```

**Comment by Shin-NiL** [comment]
A new version will be released when Godot 3.2.4 stable is done. If you guys are in a hurry, you can try compiling the plugin following the instructions on the readme.

**Comment by gamergamesz** [comment]
NOTE: if you are compiling yourself do edit activity to  ~~~activity = godot.getActivity() ~~~
I don't know java but during compiling it was giving me ~~~error: incompatible types: Godot cannot be converted to Activity
        activity = godot; ~~~  so I don't know if it's correct or not but it's working for me for Godot share.

**Comment by yazid2000** [comment]
O friends, it appears a mistake for me, what did he do and where did he carry the last woman?
Hao complain I feel frustrated



FAILURE: Build failed with an exception.

* What went wrong:
Could not create service of type ScriptPluginFactory using BuildScopeServices.createScriptPluginFactory().
> Could not create service of type CrossBuildFileHashCache using BuildSessionScopeServices.createCrossBuildFileHashCache().

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 9s

Exit Code: 1

**Comment by yazid2000** [comment]
![Untitled](https://user-images.githubusercontent.com/78221432/106298439-2b68de80-6254-11eb-883c-600f3c744549.png)

**Comment by Shin-NiL** [comment]
New version released.
